### ISSUE TITLE
[Ubuntu 22.10] - Theme applied to everything except Terminal

### ISSUE THREAD

**Issue by diorcula** [rose-pine/gtk#22]
The theme is nicely applied to every app i have.

There are however some weird things going on:
- not applied to the Gnome Terminal?
- When applying the theme, and checking the GTK3 Applications (adw-gtk3 theme is required), I get asked to logout. I agree to this and nothing happens?

Cheers and happy Halloween!

**edit**
after some fiddling around and running `sudo flatpak install adw-gtk3` rebooting and reapplying the theme there are still big inconsistencies:

The theme is still not applied to the Terminal, but now it does apply the menu buttons, be it that they are very very big.

![image](https://user-images.githubusercontent.com/32682696/199041071-60bbe436-9aec-402f-a5b7-bf41d682325d.png)

**Comment by Saladin1812** [comment]
Instead of using the gtk3 rose pine theme 
what i recommend is simply use the gtk4 css theme.. and use adw-gtk3-dark 

then in order for gtk 3 apps to follow the gtk 4 css you can 
`ln -s ~/.config/gtk-4.0/gtk.css ~/.config/gtk-3.0/gtk.css`

for flatpak applications you can 
`sudo flatpak override --filesystem=xdg-config/gtk-3.0 && sudo flatpak override --filesystem=xdg-config/gtk-4.0`

You can also do this using flatseal.

This is how gnome terminal gtk 3 looks and other gtk 3 applications.. 

This way all your gtk3 and gtk4 apps follow the more modern gtk 4 look and also only needs to you to get the gtk4 rosepine css and adw-gtk3 as your legacy theme.. all your apps look consistent. 

![Screenshot from 2023-04-10 23-46-45](https://user-images.githubusercontent.com/40650341/230965775-dbd2e82b-6c4e-4bbd-a1ba-38a1944054b6.png)
@diorcula

**Comment by diorcula** [comment]
@shuriken1812 Thanks for the reply!
I have since then abandoned working on it/with it and just use the standard themes from Ubuntu.
Also since Libwaita and gnome 42 gave me such headaches with not being able to theme at all that i didn't found it worth my time anymore.

I see you managed to fix it so i will close the issue!
nice job mannn :)

**Comment by Saladin1812** [comment]
> Instead of using the gtk3 rose pine theme what i recommend is simply use the gtk4 css theme.. and use adw-gtk3-dark
> 
> then in order for gtk 3 apps to follow the gtk 4 css you can `ln -s ~/.config/gtk-4.0/gtk.css ~/.config/gtk-3.0/gtk.css`
> 
> for flatpak applications you can `sudo flatpak override --filesystem=xdg-config/gtk-3.0 && sudo flatpak override --filesystem=xdg-config/gtk-4.0`
> 
> You can also do this using flatseal.
> 
> This is how gnome terminal gtk 3 looks and other gtk 3 applications..
> 
> This way all your gtk3 and gtk4 apps follow the more modern gtk 4 look and also only needs to you to get the gtk4 rosepine css and adw-gtk3 as your legacy theme.. all your apps look consistent.
> 
> ![Screenshot from 2023-04-10 23-46-45](https://user-images.githubusercontent.com/40650341/230965775-dbd2e82b-6c4e-4bbd-a1ba-38a1944054b6.png) @diorcula

@mvllow This feels alot more consistent can I add these instructions in the README ? So people have better GTK3 and GTK4 consistency ? I won't remove the old implementation, just add a note..

**Comment by ThatOneCalculator** [comment]
Sure
