### ISSUE TITLE
Sexual comment in index.theme

### ISSUE THREAD

**Issue by poach3r** [rose-pine/gtk#31]
In gtk3/rose-pine-gtk/index.theme there is the following comment: "A partially sexual act; when a female (of any species; mostly humanoids) rubs the ears/lobes of a male Ferengi, creating sensual emotions and chemical reactions in the male (and sometimes in the female).", what the hell is this?

**Comment by ThatOneCalculator** [comment]
I'm so sorry about that. That seems to be snuck in from  61d483e0b63d161c351ba68eab905bb00da1d0e8 , which was a pull request with thousands of lines of changes. They'll promptly be banned from contributing. I'm out of the house right now, but I'll be able to fix it later today.

**Comment by mvllow** [comment]
They have been blocked from contributing to Rosé Pine. I apologise for letting this slip through and thank you @ThatOneCalculator for promptly alerting the rest of the team. Thank you @poach3r for catching this and again, we are sorry.

**Comment by ThatOneCalculator** [comment]
@poach3r thank you so much for pointing that out. Since they did contribute to some other repositories, I did a search on our org in Github and thankfully that was the only violation I was able to find.

![](https://media.discordapp.net/attachments/1090685348306239592/1187855660235358280/image.png?ex=659867ca&is=6585f2ca&hm=b5abb19fbbaf4ebc6384547993a542cad389d56c1c49ed2869f81cfd790d9128&=&format=webp&quality=lossless&width=634&height=367)

**Comment by ThatOneCalculator** [comment]
Update: this was NOT @ashbork 's fault. A theme template called "oomox" was used, and in some versions of it, had that comment built-in. 

![image](https://github.com/rose-pine/gtk/assets/44733677/b3043c14-a157-4475-9bf8-c6e12ffcb005)

**Comment by ashbork** [comment]
Thank you for the clarification, can't wrap my head around why that was a thing in the template 😅

**Comment by ThatOneCalculator** [comment]
It seems to be some weird Star Trek reference
